name: Build Modules

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install BrainSlug
        run: | 
          git clone https://github.com/Chadderz121/brainslug-wii
          cd brainslug-wii
          make install
          cd ..

      - name: Compile
        run: |
          make
          cp */bin/*.mod .

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with: 
          name: modules
          path: |
            *.mod