name: Build Modules

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up devkitPPC
        run: | 
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S wii-dev --noconfirm

      - name: Install BrainSlug
        run: | 
          git clone https://github.com/Chadderz121/brainslug-wii
          cd brainslug-wii
          DEVKITPRO=/opt/devkitpro DEVKITPPC=/opt/devkitpro/devkitPPC sudo make install
          cd ..

      - name: Compile
        run: |
          DEVKITPRO=/opt/devkitpro DEVKITPPC=/opt/devkitpro/devkitPPC make
          cp */bin/*.mod .

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with: 
          name: modules
          path: |
            *.mod